networks:
  default:
    name: tk-proxy
    external: true

services:
  open-resume:
    build:
      context: ./open-resume-source
      dockerfile: Dockerfile
    container_name: open-resume
    image: open-resume
    labels:
      traefik.enable: true
      traefik.http.routers.open-resume.entrypoints: https
      traefik.http.routers.open-resume.rule: Host(`open-resume.local.xerogravity.space`) || Host(`open-resume.ts.xerogravity.space`) || Host(`open-resume.cf.xerogravity.space`)
      traefik.http.routers.open-resume.service: open-resume
      traefik.http.routers.open-resume.tls: true
      traefik.http.services.open-resume.loadbalancer.server.port: 3000
    restart: unless-stopped